### ISSUE TITLE
Q4 2018

### ISSUE THREAD

**Issue by carolynponce** [vic123/Blackboard-Grade-Center-Due-Dates#2]
Hi, 
We are getting the following error on Q4 2018 CU 4. 
We are running version 0.9.32 of the B2 and have tried the two newest versions listed here. All three versions give the same error. 

Unable to compile class for JSP:

An error occurred at line: 279 in the jsp file: /gc_duedates.jsp
RECEIPT_KEY cannot be resolved or is not a field
276: ReceiptMessage.messageTypeEnum.WARNING);
277: } else rm = new ReceiptMessage("Changes Saved", ReceiptMessage.messageTypeEnum.SUCCESS);
278: ro.addMessage(rm);
279: request.getSession().setAttribute(InlineReceiptTag.RECEIPT_KEY, ro);
280: //logForward(LogService.Verbosity.DEBUG, "response.sendRedirect" + formURL + "&uuid=" + sessionTag.randomUUID);
281: // Retrieve the course identifier from the URL and construct formURL for response.sendRedirect(formURL) to itself
282: String formURL = request.getRequestURL().toString() + "?course_id="

Stacktrace:

For reference, the Error ID is f40f871a-75ad-492f-8cac-40d86ed23d86.

Tuesday, April 9, 2019 9:20:16 AM CDT

**Comment by vic123** [comment]
Should be fixed in https://github.com/vic123/Blackboard-Grade-Center-Due-Dates/releases/tag/v.1.0.0 , please report on any new issues and sorry for the delay.
