### ISSUE TITLE
Need Q4 2018 (3500) DVM

### ISSUE THREAD

**Issue by vic123** [vic123/Blackboard-Grade-Center-Due-Dates#3]
I think already more than 5 institutions have asked me for fixing of incompatibility with this release.
Can anybody share with me the DVM image or enough access to remote instance for debugging?

**Comment by kblobaum** [comment]
I sometimes use the resource below that Blackboard now provides for free to developers , it is a virtual machine you can rent on the Amazon cloud for 10 cents an hour. Just make sure your shut it down after your done and you can remove the instance if you don't want to get a small storage fee. 

This is the 3700 release (Q2, 2019) but I believe it will probably fail just the same as the 3500 (Q4, 2018) release.  

https://aws.amazon.com/marketplace/seller-profile?id=f6f7de05-e6d2-47f8-96e8-51cc4b38182b

https://community.blackboard.com/docs/DOC-4242-using-the-blackboard-learn-ami-for-rest-and-lti-development

Hope that helps maybe someone else has a better solution. 
Thanks,
Kevin

**Comment by vic123** [comment]
I did not give it a try yet because Blackboard noted that it does not have enough permissions for BB development. 
https://community.blackboard.com/docs/DOC-1649-developer-virtual-machine-dvm
“If you prefer the Virtual Machine, or you wish to develop Building Blocks, you must first be a contracted client or partner.”
Basically an exception looks like a pure JSP problem, do anybody know if I can at least to install custom BB on AWS image?

**Comment by kblobaum** [comment]
I think I have installed B2's using this version in the past.  Edit/: this is incorrect
Kevin

**Comment by kblobaum** [comment]
Sorry I guess I am wrong I just tried it and your hunch is correct you cannot install B2's using the AMI for REST and LTI development in the Amazon Cloud.  
Kevin

**Comment by sutekidayo** [comment]
Blackboard has not released their DVM for Q4 2018 yet, but I have built one from upgrading from Q2 2018.  I've shared a Google Drive file with you.

**Comment by vic123** [comment]
Thank you very much @sutekidayo ! 
I've downloaded and checked that it is starting fine, you can delete GD share.
