### ISSUE TITLE
Availability Toggle Unreliable

### ISSUE THREAD

**Issue by mabilan** [vic123/Blackboard-Grade-Center-Due-Dates#5]
Due date updates are correctly reflected when updates are submitted, however updates to the "Is it available?" column are not reliably pushed through.

If an item is made unavailable with the tool it may or may not have its availability adjusted. If it is not, the tool will still assert the "adjusted" availability setting (e.g. Tool indicates available when still unavailable, or vice versa).

**Comment by vic123** [comment]
I've checked it , it is a naming problem, column name is not correct, it adjusts visibility in the grade book and do not have any effect on the course item availability. 
Probably should be renamed.
Thank you for the signal and sorry for the delay - nobody else has complained, and I was lazing so on.
